project_id = "oklgqelcaujxntgjyuis"

[functions.admin-push-send]
verify_jwt = false

[functions.push-subscribe]
verify_jwt = false

[functions.push-notify]
verify_jwt = false

[functions.mobile-version]
verify_jwt = false

[functions.auto-notifications]
verify_jwt = false


[functions.ai-chat]
verify_jwt = false
