
CREATE SCHEMA IF NOT EXISTS extensions;
DROP EXTENSION IF EXISTS http CASCADE;
CREATE EXTENSION http WITH SCHEMA extensions;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA extensions FROM PUBLIC, anon, authenticated;
